services:
  badger:
    build: .
    environment:
      CONFIG_PATH: /example_config.yml
    volumes:
      - ./example_config.yml:/example_config.yml
      - ./example_assets:/example_assets
    ports:
      - "80:80"