# Application to expose
apiVersion: apps/v1
kind: Deployment
metadata:
    name: dev-badges
    namespace: dev-backend
spec:
    replicas: 1 #number of instances running
    strategy:
        rollingUpdate:
            maxSurge: 1 # as an absolute number of replicas
            maxUnavailable: 33% # as % of replicas
        type: RollingUpdate
    selector:
        matchLabels:
            app: dev-backend
    template:
        metadata:
            labels:
                app: dev-backend
        spec:
            containers:
                - name: dev-backend
                  image: rfrdockerregistery.azurecr.io/rfr_backend_badges:main
                  imagePullPolicy: Always
                  ports:
                      - containerPort: 80
            imagePullSecrets:
                - name: acr-secret-dev
            tolerations:
                - effect: NoSchedule
                  key: app
                  operator: Equal
                  value: develop

---
# Service to reach the application on the cluster
apiVersion: v1
kind: Service
metadata:
    name: prod-badges
    namespace: prod-backend
    labels:
        app: prod-badges
spec:
    type: ClusterIP
    selector:
        app: prod-badges
    ports:
        - name: http
          port: 80
          targetPort: 80
          protocol: TCP

# Application to expose
apiVersion: apps/v1
kind: Deployment
metadata:
    name: prod-badges
    namespace: prod-backend
spec:
    replicas: 1 #number of instances running
    strategy:
        rollingUpdate:
            maxSurge: 1 # as an absolute number of replicas
            maxUnavailable: 33% # as % of replicas
        type: RollingUpdate
    selector:
        matchLabels:
            app: prod-backend
    template:
        metadata:
            labels:
                app: prod-backend
        spec:
            containers:
                - name: prod-backend
                  image: rfrdockerregistery.azurecr.io/rfr_backend_badges:main
                  imagePullPolicy: Always
                  ports:
                      - containerPort: 80
            imagePullSecrets:
                - name: acr-secret-prod
            tolerations:
                - effect: NoSchedule
                  key: app
                  operator: Equal
                  value: develop

---
# Service to reach the application on the cluster
apiVersion: v1
kind: Service
metadata:
    name: prod-badges
    namespace: prod-backend
    labels:
        app: prod-badges
spec:
    type: ClusterIP
    selector:
        app: prod-badges
    ports:
        - name: http
          port: 80
          targetPort: 80
          protocol: TCP

          
