on:
    push:
        branches:
            - main
        # tags:
        # - v*

name: Build and publish Development

jobs:
    build-and-publish:
        name: Build and publish Docker image
        runs-on: ubuntu-latest
        environment: Development
        steps:
            - name: Checkout
              uses: actions/checkout@main
            - name: Give permissions to gradlew (Samufix 2000)
              run: chmod a+rx ./gradlew 
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v2
            - name: Set up Docker Buildx
              id: buildx
              uses: docker/setup-buildx-action@v2
            - name: Set Docker image meta tags
              id: meta
              uses: docker/metadata-action@v4
              with:
                  flavor: latest=true
                  images: ${{ secrets.REGISTRY_LOGIN_SERVER }}/rfr_backend_badges
                  tags: |
                      type=ref,event=branch
            - name: Login to ACR
              uses: docker/login-action@v3
              with:
                  registry: ${{ secrets.REGISTRY_LOGIN_SERVER }}
                  username: ${{ secrets.REGISTRY_USERNAME }}
                  password: ${{ secrets.REGISTRY_PASSWORD }}
            - name: Push to Docker Hub
              uses: docker/build-push-action@v4
              with:
                  push: true
                  context: .
                  file: ./Dockerfile
                  platforms: linux/amd64
                  tags: ${{ steps.meta.outputs.tags }}
                  labels: ${{ steps.meta.outputs.labels }}
                  build-args: |
                      NPM_TOKEN=${{ secrets.AZURE_CREDENTIALS }}
            - name: Portainer webhook
              run: curl -sS -X POST "${{ secrets.PORTAINER_WEBHOOK }}?RESTART_AT=$(date -u +%s)"
